os: linux
language: android
jdk: oraclejdk8
env:
  global:
  - ANDROID_API=28
  - ANDROID_BUILD_API=28.0.3
  - NDK_API=21.0.6113669
  - REPO=t-e-l/termux-float
  - APK_NAME="TEL:Float"
android:
  components:
  - tools
  - tools
  - platform-tools
  - build-tools-${ANDROID_BUILD_API}
  - android-${ANDROID_API}
  - extra-android-m2repository
  - extra
  - extra-google-m2repository
  licenses:
  - android-sdk-license-.+
  - android-ndk-license-.+
  - android-sdk-preview-license-.+
  - google-gdk-license-.+
before_cache: "-rm -f $HOME/.gradle/caches/modules-2/modules-2.lock -rm -fr $HOME/.gradle/caches/*/plugin-resolution/"
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"
script:
- "./gradlew :app:assembleRelease"
before_install:
- openssl aes-256-cbc -K $encrypted_c80f59e584b7_key -iv $encrypted_c80f59e584b7_iv -in keystore.jks.enc -out keystore.jks -d
- mkdir -p $ANDROID_HOME/licenses
- echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > $ANDROID_HOME/licenses/android-sdk-license
- echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> $ANDROID_HOME/licenses/android-sdk-license
- echo y | sdkmanager "platforms;android-${ANDROID_API}"
- echo y | sdkmanager "ndk-bundle"
- echo y | sdkmanager "ndk;${NDK_API}"
before_deploy:
- find . -name '*.apk'
- mv ./app/build/outputs/apk/release/app-release-unsigned.apk app-release.apk
- jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore keystore.jks -storepass
  $keystore_password -keypass $keystore_alias_password app-release.apk $keystore_alias
- jarsigner -verify app-release.apk
- "${ANDROID_HOME}build-tools/${ANDROID_BUILD_API}/zipalign -v 4 app-release.apk ${APK_NAME}.apk"

deploy:
  provider: releases
  api_key:
    secure: RvH9fA+kvgbnc+gyaATU8ZXhfSamvkfNr0TSas9jYCCpkygqaiMBQrCofhJX4ZpBFXzX00ZW1RpqIkJ68QgItS0GJn2YLD5YTQ50ZrF+vcWz1OjsszUZ9tuF5alOi34UGaChgY9E7C6J9AfL14MwhmrO9oBkGpFotjc7UsZQrHpukbJr3kO1mHYZHHHD8ndEMS4dX+Z4tDkmTqkPAgKRqn8EaPxq84FxezvidX5HwlqOmHZ9ersL8PUCu0ZrpWutlshbLVRbvS+8AVcxZrYWDQCg3Ty3GfcdFay7pRb/4yqv5ueP5KAYvV1PuQ4GYpzYnQRfGckd/qjel7pC1+sE3lyW98iq5Z2fDr2TLEA/yH1kiLkQRKU658VHzuSiRFpui7scJ7B3c1fPkcG/kLhy5KCeYC4GPPda5jwXD53dw0e7eRGLDS+r2SGoBUgI5cKWvHJtpc+UJecK1cYyeQXSUrjxpePKyGQxAJ3hVMj6XH8zrGqicnjXEDkUzG2oL2NwQP1BAP6eTA9anwI/+yrr2lkMT6sWStoOrM8TGpSXG4hU47RdLT46K6dCNhcjUi1cg1NqZd9YG6/me3rdV68AMmmjotTVz3xEhYmx+2sIdgCJO6ZwHp/20JBW2uB6YaliGwHo0HBckZRHqVXAIZJHhgzPSNJH0Y3Yc3JS3iGFOqU=
  file: ${APK_NAME}.apk
  skip_cleanup: true
  on:
    repo: ${REPO}
